"""
Embedder & Database Uploader

Reads the processed JSONL chunks, generates vector embeddings using Google Vertex AI,
and uploads both the embeddings and the strict JSON metadata to Supabase (pgvector).
"""
import os
import sys
import json
from pathlib import Path
from typing import List, Dict, Any

# Add the 'src' directory to the Python path to resolve imports when running as a script
project_root = Path(__file__).parent.parent.parent.parent.parent
api_root = project_root / "apps" / "api"
sys.path.append(str(api_root))

from langchain_google_genai import GoogleGenerativeAIEmbeddings
from src.config.settings import settings

class VectorUploader:
    def __init__(self):
        # We use gemini-embedding-2 which is the latest Google embedding model for AI Studio
        self.embeddings = GoogleGenerativeAIEmbeddings(
            model="models/gemini-embedding-2",
            google_api_key=settings.google_api_key
        )
        
        # TODO: Initialize Supabase client here once credentials are set
        # from supabase import create_client, Client
        # self.supabase: Client = create_client(settings.supabase_url, settings.supabase_service_role_key)

    def load_chunks(self, input_path: str) -> List[Dict[str, Any]]:
        """Loads chunks from the JSONL file generated by the chunker."""
        chunks = []
        with open(input_path, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    chunks.append(json.loads(line))
        return chunks

    def process_and_upload(self, chunks: List[Dict[str, Any]]):
        """Generates embeddings in small batches to respect rate limits and uploads to the database."""
        import time
        
        print(f"Processing {len(chunks)} chunks for embedding...")
        
        batch_size = 100 # Maximum batch size for Gemini API
        records_to_insert = []
        
        for i in range(0, len(chunks), batch_size):
            batch_chunks = chunks[i:i+batch_size]
            texts = [chunk["content"] for chunk in batch_chunks]
            
            success = False
            while not success:
                try:
                    vectors = self.embeddings.embed_documents(texts)
                    
                    for j, chunk in enumerate(batch_chunks):
                        records_to_insert.append({
                            "content": chunk["content"],
                            "embedding": vectors[j],
                            "metadata": chunk["metadata"]
                        })
                        
                    print(f"Embedded batch {i//batch_size + 1}/{(len(chunks)//batch_size) + 1}")
                    success = True
                    
                    # Sleep slightly to stay under the 100 requests per minute limit
                    time.sleep(1.0)
                    
                except Exception as e:
                    if "429" in str(e) or "quota" in str(e).lower():
                        print(f"Rate limit (429) hit. Sleeping for 60 seconds before retrying...")
                        time.sleep(60)
                    else:
                        print(f"Fatal error during embedding: {e}")
                        raise e

        print(f"Successfully generated {len(records_to_insert)} embeddings.")
        
        # TODO: Uncomment to actually insert into Supabase once DB is ready
        # response = self.supabase.table("legal_documents").insert(records_to_insert).execute()
        # print(f"Uploaded to Supabase: {len(response.data)} records.")
        print("Ready for Supabase upload (Database credentials needed).")

if __name__ == "__main__":
    project_root = Path(__file__).parent.parent.parent.parent.parent
    input_path = project_root / "apps" / "api" / "data" / "processed" / "chunks.jsonl"
    
    if not input_path.exists():
        print(f"Error: {input_path} not found. Run chunker.py first.")
    else:
        uploader = VectorUploader()
        chunks = uploader.load_chunks(str(input_path))
        uploader.process_and_upload(chunks)
