"""
Embedder & Database Uploader

Reads the processed JSONL chunks, generates vector embeddings using Google Vertex AI,
and uploads both the embeddings and the strict JSON metadata to Supabase (pgvector).
"""
import os
import json
from pathlib import Path
from typing import List, Dict, Any
from langchain_google_vertexai import VertexAIEmbeddings
from ...config.settings import settings

class VectorUploader:
    def __init__(self):
        # We use text-embedding-004 which is the latest Google embedding model, excellent for semantic search
        self.embeddings = VertexAIEmbeddings(
            model_name="text-embedding-004",
            project=settings.google_cloud_project,
            location=settings.google_cloud_location
        )
        
        # TODO: Initialize Supabase client here once credentials are set
        # from supabase import create_client, Client
        # self.supabase: Client = create_client(settings.supabase_url, settings.supabase_service_role_key)

    def load_chunks(self, input_path: str) -> List[Dict[str, Any]]:
        """Loads chunks from the JSONL file generated by the chunker."""
        chunks = []
        with open(input_path, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    chunks.append(json.loads(line))
        return chunks

    def process_and_upload(self, chunks: List[Dict[str, Any]]):
        """Generates embeddings and uploads to the database."""
        print(f"Processing {len(chunks)} chunks for embedding...")
        
        # Extract just the text content for the embedding model
        texts = [chunk["content"] for chunk in chunks]
        
        try:
            # Generate embeddings in bulk
            vectors = self.embeddings.embed_documents(texts)
            
            # Prepare data for Supabase insertion
            records_to_insert = []
            for i, chunk in enumerate(chunks):
                record = {
                    "content": chunk["content"],
                    "embedding": vectors[i],
                    "metadata": chunk["metadata"] # The strict JSON schema lives here!
                }
                records_to_insert.append(record)
                
            print(f"Successfully generated {len(vectors)} embeddings.")
            
            # TODO: Uncomment to actually insert into Supabase once DB is ready
            # response = self.supabase.table("legal_documents").insert(records_to_insert).execute()
            # print(f"Uploaded to Supabase: {len(response.data)} records.")
            print("Ready for Supabase upload (Database credentials needed).")
            
        except Exception as e:
            print(f"Error during embedding/upload: {e}")

if __name__ == "__main__":
    project_root = Path(__file__).parent.parent.parent.parent.parent
    input_path = project_root / "apps" / "api" / "data" / "processed" / "chunks.jsonl"
    
    if not input_path.exists():
        print(f"Error: {input_path} not found. Run chunker.py first.")
    else:
        uploader = VectorUploader()
        chunks = uploader.load_chunks(str(input_path))
        uploader.process_and_upload(chunks)
