"""
Embedder & Database Uploader

Reads the processed JSONL chunks, generates vector embeddings LOCALLY using
transformers + torch directly (no sentence-transformers needed).
Zero API calls, zero rate limits.
"""
import os
import sys
import json
import time
import torch
from pathlib import Path
from typing import List, Dict, Any

# Add the 'src' directory to the Python path to resolve imports when running as a script
project_root = Path(__file__).parent.parent.parent.parent.parent
api_root = project_root / "apps" / "api"
sys.path.append(str(api_root))

from transformers import AutoTokenizer, AutoModel

class VectorUploader:
    def __init__(self):
        model_name = 'sentence-transformers/all-MiniLM-L6-v2'
        print(f"Loading local embedding model '{model_name}' (first run downloads ~80MB)...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name)
        self.model.eval()
        print("Model loaded.")

    def _mean_pooling(self, model_output, attention_mask):
        """Mean pooling - average all token embeddings weighted by attention mask."""
        token_embeddings = model_output[0]
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

    def _embed_batch(self, texts: List[str]) -> List[List[float]]:
        """Embed a batch of texts and return normalized vectors."""
        encoded = self.tokenizer(texts, padding=True, truncation=True, max_length=512, return_tensors='pt')
        with torch.no_grad():
            output = self.model(**encoded)
        embeddings = self._mean_pooling(output, encoded['attention_mask'])
        # Normalize
        embeddings = torch.nn.functional.normalize(embeddings, p=2, dim=1)
        return embeddings.cpu().numpy().tolist()

    def load_chunks(self, input_path: str) -> List[Dict[str, Any]]:
        """Loads chunks from the JSONL file generated by the chunker."""
        chunks = []
        with open(input_path, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    chunks.append(json.loads(line))
        return chunks

    def process_and_upload(self, chunks: List[Dict[str, Any]], output_path: str):
        """Generates embeddings locally in batches and saves to JSONL."""
        print(f"Processing {len(chunks)} chunks for embedding...")
        
        batch_size = 64
        all_vectors = []
        start = time.time()
        
        for i in range(0, len(chunks), batch_size):
            batch_texts = [c["content"] for c in chunks[i:i+batch_size]]
            vectors = self._embed_batch(batch_texts)
            all_vectors.extend(vectors)
            
            done = min(i + batch_size, len(chunks))
            elapsed = time.time() - start
            rate = done / elapsed if elapsed > 0 else 0
            eta = (len(chunks) - done) / rate if rate > 0 else 0
            print(f"  [{done}/{len(chunks)}] {done*100//len(chunks)}% | {rate:.0f} chunks/s | ETA: {eta:.0f}s", end='\r')
        
        elapsed = time.time() - start
        print(f"\nEmbedded {len(all_vectors)} chunks in {elapsed:.1f}s")
        
        # Save embeddings alongside metadata to a JSONL file
        with open(output_path, 'w', encoding='utf-8') as f:
            for i, chunk in enumerate(chunks):
                record = {
                    "content": chunk["content"],
                    "embedding": all_vectors[i],
                    "metadata": chunk["metadata"]
                }
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
        
        print(f"Saved {len(all_vectors)} embedded records to {output_path}")

if __name__ == "__main__":
    project_root = Path(__file__).parent.parent.parent.parent.parent
    input_path = project_root / "apps" / "api" / "data" / "processed" / "chunks.jsonl"
    output_path = project_root / "apps" / "api" / "data" / "processed" / "embedded_chunks.jsonl"
    
    if not input_path.exists():
        print(f"Error: {input_path} not found. Run chunker.py first.")
    else:
        uploader = VectorUploader()
        chunks = uploader.load_chunks(str(input_path))
        uploader.process_and_upload(chunks, str(output_path))
