"""
Hybrid Retriever — Searches the locally embedded legal corpus using cosine similarity.
Loads the embedded_chunks.jsonl generated by embedder.py and performs
real semantic search against the user's query.
"""
import json
import torch
import numpy as np
from pathlib import Path
from typing import List, Dict, Any
from transformers import AutoTokenizer, AutoModel


class HybridRetriever:
    def __init__(self):
        self._chunks = None
        self._embeddings = None
        
        # Load the same model used for embedding
        model_name = 'sentence-transformers/all-MiniLM-L6-v2'
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name)
        self.model.eval()
        
        # Load pre-computed embeddings
        self._load_embeddings()

    def _mean_pooling(self, model_output, attention_mask):
        token_embeddings = model_output[0]
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

    def _embed_query(self, text: str) -> np.ndarray:
        """Embed a single query string."""
        encoded = self.tokenizer([text], padding=True, truncation=True, max_length=512, return_tensors='pt')
        with torch.no_grad():
            output = self.model(**encoded)
        embedding = self._mean_pooling(output, encoded['attention_mask'])
        embedding = torch.nn.functional.normalize(embedding, p=2, dim=1)
        return embedding.cpu().numpy()[0]

    def _load_embeddings(self):
        """Load the pre-computed embeddings using fast binary cache or JSONL fallback and build partitioned indices."""
        import pickle
        api_dir = Path(__file__).resolve().parent.parent.parent
        processed_dir = api_dir / "data" / "processed"
        embeddings_path = processed_dir / "embedded_chunks.jsonl"
        cache_vec_path = processed_dir / "embeddings_cache.npy"
        cache_chunks_path = processed_dir / "chunks_cache.pkl"
        
        if cache_vec_path.exists() and cache_chunks_path.exists():
            print("Loading embedded corpus from fast binary cache...")
            self._embeddings = np.load(str(cache_vec_path))
            with open(cache_chunks_path, "rb") as f:
                self._chunks = pickle.load(f)
            print(f"Loaded {len(self._chunks)} chunks in milliseconds.")
        elif embeddings_path.exists():
            print("Loading embedded legal corpus from JSONL and building fast cache...")
            self._chunks = []
            vectors = []
            
            with open(embeddings_path, 'r', encoding='utf-8') as f:
                for line in f:
                    if line.strip():
                        record = json.loads(line)
                        self._chunks.append({
                            "content": record["content"],
                            "metadata": record["metadata"]
                        })
                        vectors.append(record["embedding"])
            
            self._embeddings = np.array(vectors, dtype=np.float32)
            
            # Save cache for instant future startups
            try:
                np.save(str(cache_vec_path), self._embeddings)
                with open(cache_chunks_path, "wb") as f:
                    pickle.dump(self._chunks, f, protocol=pickle.HIGHEST_PROTOCOL)
                print(f"Created fast cache: {cache_vec_path.name} & {cache_chunks_path.name}")
            except Exception as e:
                print(f"Cache save warning: {e}")
        else:
            print(f"WARNING: No embeddings found. Retriever will return empty results.")
            self._chunks = []
            self._embeddings = np.array([])
            return

        # Pre-partition indices and embedding slices for ultra-fast scoped retrieval
        self._india_indices = [
            i for i, c in enumerate(self._chunks) 
            if c["metadata"].get("jurisdiction", "").lower() == "india"
        ]
        self._global_indices = [
            i for i, c in enumerate(self._chunks) 
            if c["metadata"].get("jurisdiction", "").lower() == "global"
        ]

        if len(self._india_indices) > 0:
            self._india_embeddings = self._embeddings[self._india_indices]
        else:
            self._india_indices = list(range(len(self._chunks)))
            self._india_embeddings = self._embeddings

        if len(self._global_indices) > 0:
            self._global_embeddings = self._embeddings[self._global_indices]
        else:
            self._global_indices = list(range(len(self._chunks)))
            self._global_embeddings = self._embeddings

        print(f"Partitioned indices ready: India ({len(self._india_indices)} chunks), Global ({len(self._global_indices)} chunks).")


    def retrieve(self, query: str, jurisdiction: str = "India", top_k: int = 10) -> List[Dict[str, Any]]:
        """
        Retrieve the top-k most relevant legal documents for a given query.
        Uses pre-partitioned cosine similarity against the selected jurisdiction.
        """
        if len(self._chunks) == 0:
            return []
        
        # Determine target partition
        is_global = str(jurisdiction).lower() in ["global", "international", "pct", "wipo", "foreign"]
        target_indices = self._global_indices if is_global else self._india_indices
        target_embeddings = self._global_embeddings if is_global else self._india_embeddings
        
        # Embed the query
        query_vec = self._embed_query(query)
        
        # Fast scoped cosine similarity
        scores = target_embeddings @ query_vec
        
        # Top-k within the target jurisdiction partition
        top_local_indices = np.argsort(scores)[::-1][:top_k]
        
        results = []
        for local_idx in top_local_indices:
            orig_idx = target_indices[local_idx]
            results.append({
                "content": self._chunks[orig_idx]["content"],
                "metadata": self._chunks[orig_idx]["metadata"],
                "score": float(scores[local_idx])
            })
        
        return results


# Singleton instance
hybrid_retriever = HybridRetriever()
