"""
Hybrid Retriever — Searches the locally embedded legal corpus using cosine similarity.
Loads the embedded_chunks.jsonl generated by embedder.py and performs
real semantic search against the user's query.
"""
import json
import torch
import numpy as np
from pathlib import Path
from typing import List, Dict, Any
from transformers import AutoTokenizer, AutoModel


class HybridRetriever:
    def __init__(self):
        self._chunks = None
        self._embeddings = None
        
        # Load the same model used for embedding
        model_name = 'sentence-transformers/all-MiniLM-L6-v2'
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name)
        self.model.eval()
        
        # Load pre-computed embeddings
        self._load_embeddings()

    def _mean_pooling(self, model_output, attention_mask):
        token_embeddings = model_output[0]
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

    def _embed_query(self, text: str) -> np.ndarray:
        """Embed a single query string."""
        encoded = self.tokenizer([text], padding=True, truncation=True, max_length=512, return_tensors='pt')
        with torch.no_grad():
            output = self.model(**encoded)
        embedding = self._mean_pooling(output, encoded['attention_mask'])
        embedding = torch.nn.functional.normalize(embedding, p=2, dim=1)
        return embedding.cpu().numpy()[0]

    def _load_embeddings(self):
        """Load the pre-computed embeddings from the JSONL file."""
        project_root = Path(__file__).parent.parent.parent.parent.parent
        embeddings_path = project_root / "apps" / "api" / "data" / "processed" / "embedded_chunks.jsonl"
        
        if not embeddings_path.exists():
            print(f"WARNING: {embeddings_path} not found. Retriever will return empty results.")
            print("Run embedder.py first to generate embeddings.")
            self._chunks = []
            self._embeddings = np.array([])
            return
        
        print("Loading embedded legal corpus into memory...")
        self._chunks = []
        vectors = []
        
        with open(embeddings_path, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    record = json.loads(line)
                    self._chunks.append({
                        "content": record["content"],
                        "metadata": record["metadata"]
                    })
                    vectors.append(record["embedding"])
        
        self._embeddings = np.array(vectors, dtype=np.float32)
        print(f"Loaded {len(self._chunks)} embedded chunks.")

    def retrieve(self, query: str, jurisdiction: str = "India", top_k: int = 10) -> List[Dict[str, Any]]:
        """
        Retrieve the top-k most relevant legal documents for a given query.
        Uses cosine similarity between the query embedding and pre-computed doc embeddings.
        Optionally filters by jurisdiction.
        """
        if len(self._chunks) == 0:
            return []
        
        # Embed the query
        query_vec = self._embed_query(query)
        
        # Cosine similarity (embeddings are already normalized)
        scores = self._embeddings @ query_vec
        
        # Get top-k indices
        top_indices = np.argsort(scores)[::-1][:top_k * 3]  # Fetch extra for filtering
        
        results = []
        for idx in top_indices:
            chunk = self._chunks[idx]
            score = float(scores[idx])
            
            # Optional jurisdiction filter (soft match)
            meta_jurisdiction = chunk["metadata"].get("jurisdiction", "").lower()
            if jurisdiction and jurisdiction.lower() not in meta_jurisdiction and meta_jurisdiction != "unknown":
                continue
            
            results.append({
                "content": chunk["content"],
                "metadata": chunk["metadata"],
                "score": score
            })
            
            if len(results) >= top_k:
                break
        
        # If jurisdiction filter was too strict, fall back to unfiltered top-k
        if len(results) < 3:
            results = []
            for idx in np.argsort(scores)[::-1][:top_k]:
                results.append({
                    "content": self._chunks[idx]["content"],
                    "metadata": self._chunks[idx]["metadata"],
                    "score": float(scores[idx])
                })
        
        return results


# Singleton instance
hybrid_retriever = HybridRetriever()
